#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
float r = 0.032;
void go_straight (float distance);

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	//	motor[rightMotor] = 40;		  // Motor on port2 is run at full (127) power forward
	//	motor[leftMotor]  = 40;  // Motor on port3 is run at full (127) power forward
	//	wait1Msec(1000);		        // Robot runs previous code for 3000 milliseconds before moving on

	go_straight (0.30);
}												        // Program ends, and the robot stops
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

void go_straight (float distance)
{

	float e = (180.0*distance)/(PI*r);

	nMotorEncoder[rightMotor] = 0;
	nMotorEncoder[leftMotor] = 0;

	//While less than 1000 encoder counts of the right motor
	while(abs(nMotorEncoder[rightMotor]) < e)
	{
		//Move forward at half power
		motor[rightMotor] = 40;
		motor[leftMotor]	= 40;

	}
	motor[rightMotor] = 40;
	motor[leftMotor]	= 40;
}
